export enum ErrorType {
    NONE = "NONE",
    EXPECTED_IDENTIFIER = "EXPECTED_IDENTIFIER",
    EXPECTED_SYMBOL = "EXPECTED_SYMBOL",
    EXPECTED_EXPRESSION = "EXPECTED_EXPRESSION",
    MALFORMED_STRUCTURE = "MALFORMED_STRUCTURE"
}